name: "Jest Annotations & Coverage"
description: "Jest action adding checks and annotations to your pull requests and comment them with code coverage results."
branding:
  icon: "check"
  color: "blue"
inputs:
  test-command:
    description: "The test command to run"
    required: false
    default: "npm test"
  working-directory:
    description: "Subdirectory to run tests in"
    required: false
    default: ""
  coverage-comment:
    description: "Comment PRs with code coverage"
    required: false
    default: "true"
  coverage-artifact-save:
    description: "Save code coverage to files"
    required: false
    default: "false"
  output-type:
    description: "Results output type (json, lcov, text, clover)"
    required: false
    default: "json"
  changes-only:
    description: "Only run tests on changed files (over base branch)"
    required: false
    default: "false"
  check-name:
    description: "Status check name"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
